FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y cron

# --- 🔐 Variables MySQL
ARG MYSQL_HOST
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_DATABASE

ENV MYSQL_HOST=$MYSQL_HOST \
    MYSQL_USER=$MYSQL_USER \
    MYSQL_PASSWORD=$MYSQL_PASSWORD \
    MYSQL_DATABASE=$MYSQL_DATABASE

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
COPY cronjob /etc/cron.d/scrapy-cron
RUN chmod 0644 /etc/cron.d/scrapy-cron && crontab /etc/cron.d/scrapy-cron

RUN touch /var/log/cron.log

CMD ["cron", "-f"]

