version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinapps_db
      MYSQL_USER: cinapps_user
      MYSQL_PASSWORD: cinapps888
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cinapps_net

  scrapy:
    build:
      context: ./automatisation
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: cinapps_user
      MYSQL_PASSWORD: cinapps888
      MYSQL_DATABASE: cinapps_db
    networks:
      - cinapps_net
    command: scrapy crawl alloc_newfilms

  scrapy-cron:
    build:
      context: ./automatisation
      dockerfile: Dockerfile.cron
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: cinapps_user
      MYSQL_PASSWORD: cinapps888
      MYSQL_DATABASE: cinapps_db
    networks:
      - cinapps_net

  cinapps_api:
    build:
      context: ./cinapps_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+mysqlconnector://cinapps_user:cinapps888@db/cinapps_db
      SECRET_KEY: "supersecretkey"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    networks:
      - cinapps_net

  api_prediction:
    build:
      context: ./API_s
    ports:
      - "8001:8000"
    depends_on:
      - cinapps_api
    environment:
      SECRET_KEY: "supersecretkey"
      ALGORITHM: "HS256"
    networks:
      - cinapps_net

  cinapps:
    build:
      context: ./cinapps
    ports:
      - "8002:8000"
    depends_on:
      - db
      - cinapps_api
      - api_prediction
    environment:
      MYSQL_USER: cinapps_user
      MYSQL_PASSWORD: cinapps888
      MYSQL_HOST: db
      MYSQL_DATABASE: cinapps_db
      MYSQL_PORT: 3306
      MYSQL_RDY: 1
      API_CRUD_URL: "http://cinapps_api:8000"
      API_CRUD_USERNAME: deborah
      API_CRUD_PASSWORD: deborahdeborah
      URL_API: "http://api_prediction:8001/prediction"
    networks:
      - cinapps_net

volumes:
  db_data:

networks:
  cinapps_net:
