version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cinapps_net

  scrapy:
    build:
      context: ./automatisation
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - cinapps_net
    command: scrapy crawl alloc_newfilms
    restart: always

  scrapy-cron:
    build:
      context: ./automatisation
      dockerfile: Dockerfile.cron
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - cinapps_net
    restart: always

  cinapps_api:
    build:
      context: ./cinapps_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - cinapps_net
    restart: always

  api_prediction:
    build:
      context: ./API_s
    ports:
      - "8001:8001"
    depends_on:
      - cinapps_api
    env_file:
      - .env
    networks:
      - cinapps_net
    restart: always

  cinapps:
    build:
      context: ./cinapps
    ports:
      - "8002:8000"
    depends_on:
      - db
      - cinapps_api
      - api_prediction
    env_file:
      - .env
    networks:
      - cinapps_net
    restart: always

volumes:
  db_data:

networks:
  cinapps_net:
