name: 🚀 CI - Tests + Build & Push Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: ✅ Run API PREDICTION + Django Tests
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 📦 Install dependencies
        working-directory: cinapps
        run: |
          pip install -r requirements.txt

      - name: 🧪 Run Django tests
        working-directory: cinapps
        run: |
          python manage.py test
          
      - name: Run FastAPI tests IA + CRUD
        working-directory: API_s
        env:
          API_CRUD_USERNAME: ${{ secrets.API_CRUD_USERNAME }}
          API_CRUD_PASSWORD: ${{ secrets.API_CRUD_PASSWORD }}
          URL_API_CRUD: http://localhost:8000
          URL_API: http://localhost:8001
        run: |
          pip install -r requirements.txt

          # Lancer l'API CRUD
          uvicorn cinapps_api.main:app --host 0.0.0.0 --port 8000 --reload &
          
          # Lancer l'API de prédiction
          uvicorn main:app --host 0.0.0.0 --port 8001 --reload &

          # Attendre que les deux APIs soient prêtes
          sleep 10

          #Tester l'intégration complète
          pytest test_api_integration.py



  build-and-push:
    name: 🛠️ Build & Push Docker Images
    needs: test  # 🔐 Ne se lance que si les tests passent
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_TAG: latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔐 Connexion à Docker Hub
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: 🧱 Build & Push API CRUD
        run: |
          docker build -t $DOCKERHUB_USERNAME/cinapps_api:$IMAGE_TAG ./cinapps_api
          docker push $DOCKERHUB_USERNAME/cinapps_api:$IMAGE_TAG

      - name: 🧠 Build & Push API Prediction
        run: |
          docker build -t $DOCKERHUB_USERNAME/api_prediction:$IMAGE_TAG ./API_s
          docker push $DOCKERHUB_USERNAME/api_prediction:$IMAGE_TAG

      - name: 🎬 Build & Push Front Django
        run: |
          docker build -t $DOCKERHUB_USERNAME/cinapps:$IMAGE_TAG ./cinapps
          docker push $DOCKERHUB_USERNAME/cinapps:$IMAGE_TAG

      - name: 🐍 Build & Push Scrapy
        run: |
          docker build -t $DOCKERHUB_USERNAME/scrapy_crawler:$IMAGE_TAG ./automatisation
          docker push $DOCKERHUB_USERNAME/scrapy_crawler:$IMAGE_TAG

      - name: ⏰ Build & Push Scrapy Cron
        run: |
          docker build -f ./automatisation/Dockerfile.cron -t $DOCKERHUB_USERNAME/scrapy_cron:$IMAGE_TAG ./automatisation
          docker push $DOCKERHUB_USERNAME/scrapy_cron:$IMAGE_TAG

      - name: 🗄️ Build & Push MySQL personnalisé
        run: |
          docker build -t $DOCKERHUB_USERNAME/mysql_custom:$IMAGE_TAG ./deploiement/mysql
          docker push $DOCKERHUB_USERNAME/mysql_custom:$IMAGE_TAG

      - name: 🚪 Déconnexion de Docker
        run: docker logout
